config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do

  authenticated :user do
    root 'resolutions#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  resources :resolutions do
    resources :tasks


  resources :users
  resources :conversations do
     resources :messages
end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :resolution
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :get_resolution
    before_action :set_task, only: %i[ show edit update destroy ]

    # GET /tasks or /tasks.json
    def index
      @tasks = @resolution.tasks
    end

    # GET /tasks/1 or /tasks/1.json
    def show
    end

    # GET /tasks/new
    def new
      @task = @resolution.tasks.build
    end

    # GET /tasks/1/edit
    def edit
    end

    # POST /tasks or /tasks.json
    def create
      @task = @resolution.tasks.build(task_params)

      respond_to do |format|
        if @task.save
          format.html { redirect_to resolution_tasks_url(@resolution), notice: "task was successfully created." }
          format.json { render :show, status: :created, location: @task }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /tasks/1 or /tasks/1.json
    def update
      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to resolution_tasks_url(@resolution), notice: "task was successfully updated." }
          format.json { render :show, status: :ok, location: @task }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /tasks/1 or /tasks/1.json
    def destroy
      @task.destroy
      respond_to do |format|
        format.html { redirect_to resolution_tasks_url(@resolution), notice: "task was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_task
        @task = @resolution.tasks.find(params[:id])
      end

      def get_resolution
        @resolution=Resolution.find(params[:resolution_id])
      end
      # Only allow a list of trusted parameters through.
      def task_params
        params.require(:task).permit(:name, :task_details, :frequency)
      end
  end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_resolution
    before_action :set_task, only: %i[ show edit update destroy ]

    # GET /tasks or /tasks.json
    def index
      @tasks = @resolution.tasks
    end

    # GET /tasks/1 or /tasks/1.json
    def show
    end

    # GET /tasks/new
    def new
      @task = @resolution.tasks.build
    end

    # GET /tasks/1/edit
    def edit
    end

    # POST /tasks or /tasks.json
    def create
      @task = @resolution.tasks.build(task_params)

      respond_to do |format|
        if @task.save
          format.html { redirect_to resolution_tasks_url(@resolution), notice: "task was successfully created." }
          format.json { render :show, status: :created, location: @task }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /tasks/1 or /tasks/1.json
    def update
      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to resolution_tasks_url(@resolution), notice: "task was successfully updated." }
          format.json { render :show, status: :ok, location: @task }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /tasks/1 or /tasks/1.json
    def destroy
      @task.destroy
      respond_to do |format|
        format.html { redirect_to resolution_tasks_url(@resolution), notice: "task was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_task
        @task = @resolution.tasks.find(params[:id])
      end

      def get_resolution
        @resolution=Resolution.find(params[:resolution_id])
      end
      # Only allow a list of trusted parameters through.
      def task_params
        params.require(:task).permit(:name, :task_details, :frequency)
      end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: [@resolution, task], local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :task_details %>
    <%= form.text_area :task_details %>
  </div>

  <div class="field">
<%= form.label :frequency %>
<%= form.select :frequency, ['Weekly','Daily','Monthly'], {include_blank: 'Select Box'} %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', [@resolution, @task] %> |
<%= link_to 'Back', resolution_tasks_path(@resolution) %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Details</th>
      <th>frequency</th>
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name%></td>
        <td><%= task.task_details %></td>
        <td><%= task.frequency %></td>
        <td><%= link_to 'Show resolution', [@resolution] %></td>
        <td><%= link_to 'Edit task', edit_resolution_task_url(@resolution, task) %></td>
        <td><%= link_to 'Destroy task', [@resolution, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New task', new_resolution_task_path(@resolution) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', resolution_tasks_path(@resolution) %>

app/views/tasks/show.html.erb
<h2>The tasks for this resolution are<% @task %></h2>
<% for task in @resolution.tasks %>

<p>
  <strong>Task_name:</strong>
  <%= @task.name%>
</p>

<p>
  <strong>Task_details:</strong>
  <%= @task.task_details %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @task.frequency %>
</p>
<% end %>
<%= link_to 'Show resolution', resolutions_path (@resolution) %> |
<%= link_to 'Tasks', resolution_tasks_path (@resolution) %> |
<%= link_to 'Edit', edit_resolution_task_url(@resolution, @task) %> |
<%= link_to 'Back', resolution_tasks_path(@resolution) %>