config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do

  authenticated :user do
    root 'resolutions#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  resources :resolutions do
    resources :tasks


  resources :users
  resources :conversations do
     resources :messages
end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end
end

app/views/shared/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Get it done!!!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
    </ul>
    <span class="navbar-text">
      <%= render 'shared/layouts/login_form' %>
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
      <% else %>
        <%= link_to "Log in", "", data: {toggle: "modal", target: ".bd-example-modal-lg"} %>
      <% end %>
    </span>
  </div>
</nav>

app/views/shared/layouts/_login_form.erb
<div class="modal fade bd-example-modal-lg"tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Please Log in</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <%= form_for(resource, as: resource_name, url: session_path(resource_name),remote: true) do |f| %>
          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>

          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "current-password" %>
          </div>

          <% if devise_mapping.rememberable? %>
            <div class="field">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>
          <div class="modal-footer">
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
  <% end %>

app/views/shared/layouts/_menu.html.erb
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
  <div class="p-3">
    <% if user_signed_in? %>
      <h5>Menu</h5>
      <p><%= link_to I18n.t('views.messages.my_page'), user_path %></p>
      <p><%= link_to I18n.t('views.messages.team_build'), new_team_path %></p>

      <h5><%= I18n.t('views.messages.select_team') %></h5>
      <% (current_user.teams.blank? ? Team.where(id: 1) : current_user.teams).each do |team| %>
        <%= link_to team_path(team) do %>
          <p>
            <%= image_tag default_img(team.icon_url), size: '30x30' %>&nbsp;
            <%= team.name %>
          </p>
        <% end %>
      <% end %>

      <p>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-block' %>
      </p>
    <% end %>
  </div>
</aside>