config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do

  authenticated :user do
    root 'resolutions#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  resources :resolutions do
    resources :tasks


  resources :users
  resources :conversations do
     resources :messages
end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end
end

app/models/resolution.rb
class Resolution < ApplicationRecord
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true



end

app/controllers/resolutions_controller.rb
class ResolutionsController < ApplicationController
  before_action :set_resolution, only: %i[ show edit update destroy ]
before_action :authenticate_user!, only: [:new, :create]
#before_action:logged_in?, only:[:new,:create]
  # GET /resolutions or /resolutions.json
  def index
    @resolutions= Resolution.all
  end


  # GET /resolutions/1 or /resolutions/1.json
  def show
  #  @resolution.user_id = current_user.id(resolution_params)
  end

  # GET /resolutions/new
  def new
      @resolution = Resolution.new


    #1.times { @resolution.tasks.build }
  end

  # GET /resolutions/1/edit
  def edit
   @resolution= Resolution.find(params[:id])
  end

  # POST /resolutions or /resolutions.json
  def create
    @resolution = Resolution.new(resolution_params)
  @resolution.user_id = current_user.id
    respond_to do |format|

                if @resolution.save
          format.html { redirect_to resolutions_path, notice: "resolution was successfully created." }
          format.json { render :show, status: :created, location: @resolution }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @resolution.errors, status: :unprocessable_entity }
        end
      end
    end


  # PATCH/PUT /resolutions/1 or /resolutions/1.json
  def update
    respond_to do |format|
      if @resolution.update(resolution_params)
        format.html { redirect_to @resolution, notice: "Resolution was successfully updated." }
        format.json { render :show, status: :ok, location: @resolution }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resolution.errors, status: :unprocessable_entity }
      end
    end
end

  # DELETE /resolutions/1 or /resolutions/1.json
  def destroy
    @resolution.destroy
    respond_to do |format|
      format.html { redirect_to resolutions_url, notice: "Resolution was successfully destroyed." }
      format.json { head :no_content }
    end
end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resolution
      @resolution = Resolution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resolution_params
      params.require(:resolution).permit(:title, :details, :end_date)
    end
end

app/helpers/resolutions_helper.rb
module ResolutionsHelper
end

app/views/resolutions/_form.html.erb
<%= form_with(model: resolution, local: true) do |form| %>
  <% if resolution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resolution.errors.count, "error") %> prohibited this resolution from being saved:</h2>

      <ul>
      <% resolution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_field :details %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/resolutions/edit.html.erb
<h1>Editing Resolution</h1>

<%= render 'form', resolution: @resolution %>

<%= link_to 'Show', @resolution %> |
<%= link_to 'Back', resolutions_path %>

app/views/resolutions/index.html.erb
  <h1 class="title"> Resolutions</h1>
    <nav class="menu">


<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Details</th>
      <th class="fa-solid fa-hourglass">End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
 <div class="contents">
    <% @resolutions.each do |resolution| %>

      <tr>
        <td class="task_row scope="row"><%= resolution.title %></td>
        <td class="details_row"><%= resolution.details %></td>
        <td class="deadline_row"><%= resolution.end_date %></td>
        <td><%= link_to 'Show', resolution, class: "btn btn-primary"%></td>
        <td><%= link_to 'Edit', edit_resolution_path(resolution), class: "btn btn-secondary"%></td>
        <td><%= link_to 'Destroy', resolution, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
</div>
  </tbody>
</table>

<br>

<%= link_to 'New Resolution', new_resolution_path %>

app/views/resolutions/new.html.erb
<h1>New Resolution</h1>

<%= render 'form', resolution: @resolution %>

<%= link_to 'Back', resolutions_path %>

app/views/resolutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resolution.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @resolution.details %>
</p>

<p>
  <strong>End date:</strong>
  <%= @resolution.end_date %>
</p>


<h3>The task/tasks set to achieve this resolution are<% @task %></h3>
<% for task in @resolution.tasks %>

<p>
  <strong>Task_name:</strong>
  <%= task.name%>
</p>

<p>
  <strong>Task_details:</strong>
  <%= task.task_details %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= task.frequency %>
</p>
<% end %>
<%= link_to 'Edit', edit_resolution_path(@resolution) %> |
<%= link_to 'Add task', resolution_tasks_path(@resolution) %>
<%= link_to 'Back', resolutions_path %>